code = open(r'src\pages\Chat.jsx', encoding='utf-8').read()
code = code.replace('{ Send, Search, ArrowLeft, UserPlus, MessageCircle, Check, CheckCheck }', '{ Send, Search, ArrowLeft, UserPlus, MessageCircle, Check, CheckCheck, Mic, MicOff }')
old_ref = 'const messagesEndRef = useRef(null);'
new_ref = 'const messagesEndRef = useRef(null);\n  const [recording, setRecording] = useState(false);\n  const [audioBlob, setAudioBlob] = useState(null);\n  const [audioUrl, setAudioUrl] = useState(null);\n  const mediaRecorderRef = useRef(null);\n  const audioChunksRef = useRef([]);\n  const startRecording = async () => { try { const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); const mediaRecorder = new MediaRecorder(stream); mediaRecorderRef.current = mediaRecorder; audioChunksRef.current = []; mediaRecorder.ondataavailable = e => { if (e.data.size > 0) audioChunksRef.current.push(e.data); }; mediaRecorder.onstop = () => { const blob = new Blob(audioChunksRef.current, { type: "audio/webm" }); setAudioBlob(blob); setAudioUrl(URL.createObjectURL(blob)); stream.getTracks().forEach(t => t.stop()); }; mediaRecorder.start(); setRecording(true); } catch(e) { alert("Erro ao aceder ao microfone"); } };\n  const stopRecording = () => { if (mediaRecorderRef.current) { mediaRecorderRef.current.stop(); setRecording(false); } };\n  const cancelAudio = () => { setAudioBlob(null); setAudioUrl(null); };'
code = code.replace(old_ref, new_ref)
old_btn = '<button type="submit"'
new_btn = '<button type="button" onClick={recording ? stopRecording : startRecording} style={{ background: recording ? "#e11d48" : "#4a80d4", border: "none", borderRadius: "50%", width: 38, height: 38, display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", flexShrink: 0 }}>{recording ? <MicOff size={18} color="#fff"/> : <Mic size={18} color="#fff"/>}</button>\n                {audioUrl && !recording && (<div style={{ display: "flex", alignItems: "center", gap: 8 }}><audio src={audioUrl} controls style={{ height: 30, maxWidth: 160 }}/><button type="button" onClick={cancelAudio} style={{ background: "#e11d48", border: "none", borderRadius: "50%", width: 24, height: 24, color: "#fff", cursor: "pointer" }}>x</button></div>)}\n                <button type="submit"'
code = code.replace(old_btn, new_btn, 1)
open(r'src\pages\Chat.jsx', 'w', encoding='utf-8').write(code)
print('Feito! Tamanho:', len(code))
