import json

fixes = {
    "pt": {"role": {"member": "Membro", "newConvert": "Novo Convertido", "worker": "Obreiro", "deacon": "Diacono", "elder": "Presbitero", "evangelist": "Evangelista", "missionary": "Missionario", "pastor": "Pastor", "bishop": "Bispo", "youthLeader": "Lider de Jovens", "worshipLeader": "Lider de Louvor", "teacher": "Professor", "other": "Outro"}, "ministry": {"evangelism": "Evangelismo", "worship": "Louvor", "prayer": "Intercessao", "teaching": "Ensino", "missions": "Missoes", "children": "Criancas", "youth": "Jovens", "couples": "Casais", "social": "Acao Social", "other": "Outro"}},
    "en": {"role": {"member": "Member", "newConvert": "New Convert", "worker": "Worker", "deacon": "Deacon", "elder": "Elder", "evangelist": "Evangelist", "missionary": "Missionary", "pastor": "Pastor", "bishop": "Bishop", "youthLeader": "Youth Leader", "worshipLeader": "Worship Leader", "teacher": "Teacher", "other": "Other"}, "ministry": {"evangelism": "Evangelism", "worship": "Worship", "prayer": "Intercession", "teaching": "Teaching", "missions": "Missions", "children": "Children", "youth": "Youth", "couples": "Couples", "social": "Social Action", "other": "Other"}},
    "es": {"role": {"member": "Miembro", "newConvert": "Nuevo Convertido", "worker": "Obrero", "deacon": "Diacono", "elder": "Presbítero", "evangelist": "Evangelista", "missionary": "Misionero", "pastor": "Pastor", "bishop": "Obispo", "youthLeader": "Lider de Jovenes", "worshipLeader": "Lider de Alabanza", "teacher": "Profesor", "other": "Otro"}, "ministry": {"evangelism": "Evangelismo", "worship": "Alabanza", "prayer": "Intercesion", "teaching": "Ensenanza", "missions": "Misiones", "children": "Ninos", "youth": "Jovenes", "couples": "Parejas", "social": "Accion Social", "other": "Otro"}},
    "de": {"role": {"member": "Mitglied", "newConvert": "Neubekehrter", "worker": "Mitarbeiter", "deacon": "Diakon", "elder": "Altester", "evangelist": "Evangelist", "missionary": "Missionar", "pastor": "Pastor", "bishop": "Bischof", "youthLeader": "Jugendleiter", "worshipLeader": "Lobpreisleiter", "teacher": "Lehrer", "other": "Andere"}, "ministry": {"evangelism": "Evangelisation", "worship": "Lobpreis", "prayer": "Furbitte", "teaching": "Lehre", "missions": "Missionen", "children": "Kinder", "youth": "Jugend", "couples": "Paare", "social": "Soziale Arbeit", "other": "Andere"}},
    "fr": {"role": {"member": "Membre", "newConvert": "Nouveau Converti", "worker": "Ouvrier", "deacon": "Diacre", "elder": "Ancien", "evangelist": "Evangeliste", "missionary": "Missionnaire", "pastor": "Pasteur", "bishop": "Eveque", "youthLeader": "Leader Jeunesse", "worshipLeader": "Leader Louange", "teacher": "Enseignant", "other": "Autre"}, "ministry": {"evangelism": "Evangelisation", "worship": "Louange", "prayer": "Intercession", "teaching": "Enseignement", "missions": "Missions", "children": "Enfants", "youth": "Jeunesse", "couples": "Couples", "social": "Action Sociale", "other": "Autre"}},
    "ro": {"role": {"member": "Membru", "newConvert": "Nou Convertit", "worker": "Lucrator", "deacon": "Diacon", "elder": "Prezbiter", "evangelist": "Evanghelist", "missionary": "Misionar", "pastor": "Pastor", "bishop": "Episcop", "youthLeader": "Lider Tineret", "worshipLeader": "Lider Laudare", "teacher": "Profesor", "other": "Altul"}, "ministry": {"evangelism": "Evanghelizare", "worship": "Laudare", "prayer": "Intercesie", "teaching": "Invatatura", "missions": "Misiuni", "children": "Copii", "youth": "Tineret", "couples": "Cupluri", "social": "Actiune Sociala", "other": "Altul"}},
    "ru": {"role": {"member": "Chlen", "newConvert": "Novyy Obrashchennyy", "worker": "Rabotnik", "deacon": "Diakon", "elder": "Stareyshina", "evangelist": "Evangelist", "missionary": "Missionyer", "pastor": "Pastor", "bishop": "Episkop", "youthLeader": "Lider Molodezhi", "worshipLeader": "Lider Pok", "teacher": "Uchitel", "other": "Drugoy"}, "ministry": {"evangelism": "Evangelizatsiya", "worship": "Pokloneniye", "prayer": "Zastupnichestvo", "teaching": "Obucheniye", "missions": "Missii", "children": "Deti", "youth": "Molodezh", "couples": "Pary", "social": "Sotsialnaya", "other": "Drugoe"}}
}

for lang, sections in fixes.items():
    fname = "src/i18n/" + lang + ".json"
    with open(fname, "r", encoding="utf-8-sig") as f:
        data = json.load(f)
    for section, keys in sections.items():
        data[section] = keys
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print("OK: " + lang)
