import React, { useEffect, useMemo, useState } from 'react';
import { HeartHandshake, HandHeart, ShieldCheck, Send, UsersRound, X, MapPin, PackageOpen, HeartPulse, Utensils, Bus, Home, CircleHelp } from 'lucide-react';
import { useAuth } from '../context/AuthContext';

const API = `${import.meta.env.VITE_API_URL || ''}/api`;
const CATEGORIES = { food: { label: 'Alimentação', Icon: Utensils, color: '#d97706' }, health: { label: 'Saúde e medicamentos', Icon: HeartPulse, color: '#cc4b5b' }, transport: { label: 'Transporte', Icon: Bus, color: '#3876b9' }, housing: { label: 'Moradia', Icon: Home, color: '#377f70' }, essentials: { label: 'Necessidades básicas', Icon: PackageOpen, color: '#7c5ab5' }, other: { label: 'Outro apoio', Icon: CircleHelp, color: '#60747a' } };
const STATUS = { open: { label: 'Precisa de apoio', color: '#b65a37' }, in_progress: { label: 'Em acompanhamento', color: '#a87918' }, completed: { label: 'Resolvido', color: '#268158' } };
const ago = (value) => { const m = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 60000)); return m < 1 ? 'agora' : m < 60 ? `${m} min` : m < 1440 ? `${Math.floor(m / 60)} h` : `${Math.floor(m / 1440)} d`; };

export default function AjudaUmaVida() {
  const { user, token } = useAuth();
  const [posts, setPosts] = useState([]), [tab, setTab] = useState('all'), [open, setOpen] = useState(false), [loading, setLoading] = useState(true), [notice, setNotice] = useState(''), [supporters, setSupporters] = useState({}), [offerId, setOfferId] = useState(null), [offerMessage, setOfferMessage] = useState('');
  const [form, setForm] = useState({ content: '', category: 'food', is_anonymous: false, is_urgent: false });
  const headers = token ? { Authorization: `Bearer ${token}` } : {};
  const visible = useMemo(() => posts.filter((post) => tab === 'all' || post.category === tab), [posts, tab]);
  const load = async () => { setLoading(true); try { const r = await fetch(`${API}/help-posts`, { headers }); const d = await r.json(); setPosts((d.posts || []).filter((post) => post.post_type === 'social_help')); } catch { setPosts([]); } setLoading(false); };
  useEffect(() => { load(); }, [token]);
  const publish = async () => { if (!form.content.trim()) return setNotice('Escreve o que precisas e como alguém pode ajudar.'); try { const r = await fetch(`${API}/help-posts`, { method: 'POST', headers: { ...headers, 'Content-Type': 'application/json' }, body: JSON.stringify({ content: form.content, category: form.category, post_type: 'social_help', is_anonymous: form.is_anonymous, is_urgent: form.is_urgent }) }); const d = await r.json(); if (!r.ok) throw new Error(d.error || 'Não foi possível publicar.'); setOpen(false); setNotice('Pedido publicado. As pessoas podem oferecer ajuda sem ver os teus contactos privados.'); setTimeout(() => setNotice(''), 5500); load(); } catch (e) { setNotice(e.message || 'Não foi possível publicar.'); } };
  const offerHelp = async () => { const id = offerId; try { const r = await fetch(`${API}/help-posts/${id}/offer-help`, { method: 'POST', headers: { ...headers, 'Content-Type': 'application/json' }, body: JSON.stringify({ message: offerMessage }) }); const d = await r.json(); if (!r.ok) throw new Error(d.error || 'Não foi possível enviar.'); setOfferId(null); setOfferMessage(''); setNotice(d.already_offered ? 'Já tinhas demonstrado interesse em ajudar esta pessoa.' : 'A tua oferta foi enviada. A pessoa decide se quer aceitar e entrar em contacto.'); setTimeout(() => setNotice(''), 5000); } catch (e) { setNotice(e.message || 'Não foi possível enviar.'); } };
  const updateStatus = async (id, status) => { const r = await fetch(`${API}/help-posts/${id}/help-status`, { method: 'POST', headers: { ...headers, 'Content-Type': 'application/json' }, body: JSON.stringify({ status }) }); const d = await r.json(); if (r.ok) setPosts((all) => all.map((post) => post.id === id ? { ...post, help_status: d.help_status } : post)); };
  const showSupporters = async (id) => { if (supporters[id]) return setSupporters((all) => ({ ...all, [id]: null })); const r = await fetch(`${API}/help-posts/${id}/supporters`, { headers }); const d = await r.json(); if (r.ok) setSupporters((all) => ({ ...all, [id]: d.supporters || [] })); };

  return <main style={{ maxWidth: 1000, margin: '0 auto', padding: '22px 16px 48px', color: '#26383c' }}>
    <section style={{ borderRadius: 24, padding: '30px clamp(20px,5vw,46px)', background: 'linear-gradient(122deg,#174c4d,#3a7e70 58%,#9aae70)', color: '#fff', boxShadow: '0 16px 36px rgba(30,79,72,.17)' }}><span style={{ display: 'inline-flex', gap: 7, alignItems: 'center', fontWeight: 800, fontSize: 13 }}><HeartHandshake size={17}/> AÇÃO SOCIAL · SIGO COM FÉ</span><h1 style={{ fontSize: 'clamp(1.85rem,4vw,2.85rem)', lineHeight: 1.05, margin: '12px 0 10px' }}>Ajuda uma Vida</h1><p style={{ maxWidth: 650, fontSize: '1.05rem', lineHeight: 1.6, margin: 0 }}>Pessoas e igrejas unidas para apoiar necessidades reais: alimentação, saúde, medicamentos, transporte, moradia e cuidados essenciais.</p><div style={{ display: 'flex', flexWrap: 'wrap', gap: 10, marginTop: 22 }}><span style={pill}><ShieldCheck size={16}/> apoio sem expor contactos</span><span style={pill}><UsersRound size={16}/> voluntários da comunidade</span><span style={pill}><HandHeart size={16}/> acompanhamento até resolver</span></div></section>
    <section style={{ display: 'grid', gridTemplateColumns: '1.2fr .8fr', gap: 14, margin: '18px 0' }}><div style={panel}><b style={{ fontSize: 17 }}>Precisas de apoio agora?</b><p style={muted}>Cria um pedido objetivo. Quem quiser ajudar demonstra interesse; os teus dados pessoais continuam privados.</p><button onClick={() => { if (!user) return window.alert('Entra na tua conta para criar um pedido de ajuda.'); setForm({ content: '', category: 'food', is_anonymous: false, is_urgent: false }); setOpen(true); }} style={primary}><Send size={17}/> Pedir ajuda</button></div><div style={{ ...panel, background: '#fff9ed' }}><b style={{ fontSize: 17 }}>Queres ajudar alguém?</b><p style={muted}>Escolhe um pedido, oferece o que podes fazer e a pessoa decide aceitar o apoio.</p><span style={{ color: '#88621f', fontWeight: 750, fontSize: 13 }}>Nunca envies dinheiro por pressão.</span></div></section>
    {notice && <div style={{ margin: '15px 0', padding: 14, borderRadius: 13, background: '#e9f6ee', color: '#17613f', fontWeight: 700 }}>{notice}</div>}
    <div style={{ display: 'flex', gap: 8, overflowX: 'auto', paddingBottom: 7, margin: '17px 0' }}><button onClick={() => setTab('all')} style={tab === 'all' ? activeChip : chip}>Todos</button>{Object.entries(CATEGORIES).map(([key, item]) => <button key={key} onClick={() => setTab(key)} style={tab === key ? activeChip : chip}>{item.label}</button>)}</div>
    {loading ? <Empty text="A carregar pedidos de apoio..."/> : visible.length === 0 ? <Empty text="Ainda não há pedidos nesta categoria. A comunidade está pronta para ajudar."/> : <section style={{ display: 'grid', gap: 13 }}>{visible.map((post) => <HelpCard key={post.id} post={post} currentUser={user} onOffer={() => { if (!user) return window.alert('Entra na tua conta para oferecer ajuda.'); setOfferId(post.id); setOfferMessage(''); }} onStatus={updateStatus} onSupporters={showSupporters} supporters={supporters[post.id]}/>)}</section>}
    <section style={{ marginTop: 24, padding: 18, borderRadius: 17, border: '1px solid #d7e5df', background: '#f8fcfa' }}><b>Como protegemos as pessoas</b><ul style={{ color: '#607279', lineHeight: 1.65, marginBottom: 0 }}><li>Não são permitidos dados bancários, documentos, moradas nem informação médica detalhada.</li><li>O contacto só deve acontecer depois de a pessoa aceitar a oferta de ajuda.</li><li>Pedidos urgentes de saúde ou perigo devem também procurar os serviços de emergência locais.</li><li>Denuncia pedidos falsos, assédio ou tentativas de fraude.</li></ul></section>
    {open && <div style={overlay}><section style={modal}><button onClick={() => setOpen(false)} style={close}><X/></button><span style={{ color: '#347667', fontWeight: 800, fontSize: 13 }}>PEDIDO DE APOIO SOCIAL</span><h2 style={{ margin: '8px 0' }}>Como podemos ajudar?</h2><p style={muted}>Escreve apenas o necessário. Não publiques PIX, telefone, morada, documentos nem receitas médicas.</p><label style={label}>Tipo de necessidade<select value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} style={input}>{Object.entries(CATEGORIES).map(([key, item]) => <option key={key} value={key}>{item.label}</option>)}</select></label><label style={label}>Explica a necessidade<textarea rows={5} value={form.content} onChange={(e) => setForm({ ...form, content: e.target.value })} placeholder="Ex.: Preciso de uma cesta básica esta semana para a minha família..." style={{ ...input, resize: 'vertical' }}/></label><div style={{ display: 'flex', flexWrap: 'wrap', gap: 15, margin: '14px 0' }}><label><input type="checkbox" checked={form.is_anonymous} onChange={(e) => setForm({ ...form, is_anonymous: e.target.checked })}/> Publicar como anónimo</label><label><input type="checkbox" checked={form.is_urgent} onChange={(e) => setForm({ ...form, is_urgent: e.target.checked })}/> É urgente</label></div><button onClick={publish} style={{ ...primary, width: '100%', justifyContent: 'center' }}><Send size={17}/> Publicar pedido de ajuda</button></section></div>}
    {offerId && <div style={overlay}><section style={modal}><button onClick={() => setOfferId(null)} style={close}><X/></button><span style={{ color: '#347667', fontWeight: 800, fontSize: 13 }}>OFERECER APOIO</span><h2 style={{ margin: '8px 0' }}>O que consegues fazer?</h2><p style={muted}>A pessoa recebe a tua oferta. Não partilhes dinheiro nem contactos nesta mensagem.</p><textarea rows={4} value={offerMessage} onChange={(e) => setOfferMessage(e.target.value)} placeholder="Ex.: Posso entregar alimentos esta semana / posso acompanhar ao hospital..." style={{ ...input, resize: 'vertical' }}/><button onClick={offerHelp} style={{ ...primary, marginTop: 15, width: '100%', justifyContent: 'center' }}><HandHeart size={17}/> Enviar oferta de ajuda</button></section></div>}
  </main>;
}

function HelpCard({ post, currentUser, onOffer, onStatus, onSupporters, supporters }) { const cat = CATEGORIES[post.category] || CATEGORIES.other; const st = STATUS[post.help_status] || STATUS.open; const Icon = cat.Icon; const own = currentUser?.id === post.user_id; return <article style={{ padding: 18, borderRadius: 18, background: '#fff', border: post.is_urgent ? '2px solid #e16b50' : '1px solid #dfeae6', boxShadow: '0 4px 16px rgba(35,77,66,.055)' }}><header style={{ display: 'flex', alignItems: 'center', gap: 10 }}><span style={{ display: 'grid', placeItems: 'center', width: 40, height: 40, borderRadius: 12, color: cat.color, background: `${cat.color}18` }}><Icon size={21}/></span><div style={{ flex: 1 }}><b>{post.is_anonymous ? 'Pessoa da comunidade' : post.author_name || 'Membro'}</b><small style={{ display: 'block', color: '#87979a', marginTop: 2 }}>{ago(post.created_at)}</small></div><span style={{ color: st.color, background: `${st.color}13`, borderRadius: 999, padding: '5px 9px', fontWeight: 800, fontSize: 12 }}>{st.label}</span></header>{post.is_urgent && <p style={{ margin: '12px 0 0', color: '#b94d34', fontWeight: 850, fontSize: 12 }}>● PEDIDO URGENTE</p>}<p style={{ color: '#33474a', lineHeight: 1.62, margin: '13px 0' }}>{post.content}</p><footer style={{ display: 'flex', flexWrap: 'wrap', gap: 8, borderTop: '1px solid #edf2f0', paddingTop: 12 }}>{own ? <><button onClick={() => onSupporters(post.id)} style={secondary}><UsersRound size={16}/> {supporters ? 'Fechar voluntários' : 'Ver quem quer ajudar'}</button><select value={post.help_status || 'open'} onChange={(e) => onStatus(post.id, e.target.value)} style={{ ...secondary, cursor: 'pointer' }}><option value="open">Ainda preciso de apoio</option><option value="in_progress">Estou a receber apoio</option><option value="completed">Pedido resolvido</option></select></> : post.help_status !== 'completed' ? <button onClick={onOffer} style={primary}><HandHeart size={16}/> Quero ajudar</button> : <span style={{ color: '#268158', fontWeight: 800 }}>✓ Pedido resolvido</span>}</footer>{supporters && <div style={{ marginTop: 12, paddingTop: 11, borderTop: '1px solid #e7efeb' }}><b style={{ fontSize: 13 }}>Pessoas que ofereceram ajuda</b>{supporters.length === 0 ? <p style={muted}>Ainda ninguém se ofereceu.</p> : supporters.map((person) => <div key={person.id} style={{ marginTop: 9, padding: 10, borderRadius: 10, background: '#f3faf6' }}><b>{person.full_name}</b>{person.message && <small style={{ display: 'block', color: '#536d68', marginTop: 3 }}>{person.message}</small>}</div>)}</div>}</article>; }
function Empty({ text }) { return <div style={{ padding: 44, textAlign: 'center', borderRadius: 18, border: '1px dashed #c9dcd5', background: '#fff', color: '#73868a' }}><HeartHandshake size={36} color="#5c9a82"/><p>{text}</p></div>; }
const pill = { display: 'inline-flex', alignItems: 'center', gap: 6, background: 'rgba(255,255,255,.16)', padding: '7px 10px', borderRadius: 999, fontSize: 13, fontWeight: 700 };
const panel = { padding: 18, borderRadius: 17, background: '#fff', border: '1px solid #dce9e5', boxShadow: '0 4px 14px rgba(35,77,66,.05)' };
const muted = { color: '#64767b', lineHeight: 1.55, fontSize: 14 };
const primary = { border: 0, display: 'inline-flex', alignItems: 'center', gap: 7, borderRadius: 11, padding: '10px 14px', color: '#fff', background: '#2c7561', fontWeight: 850, cursor: 'pointer' };
const secondary = { border: '1px solid #cfe0da', display: 'inline-flex', alignItems: 'center', gap: 7, borderRadius: 10, padding: '8px 10px', color: '#41665c', background: '#fff', fontWeight: 750 };
const chip = { border: '1px solid #d7e4df', background: '#fff', color: '#526a68', borderRadius: 999, padding: '9px 13px', whiteSpace: 'nowrap', fontWeight: 750, cursor: 'pointer' };
const activeChip = { ...chip, border: 0, background: '#2c7561', color: '#fff' };
const overlay = { position: 'fixed', zIndex: 1000, inset: 0, background: 'rgba(17,45,38,.55)', display: 'grid', placeItems: 'center', padding: 16 };
const modal = { position: 'relative', width: 'min(590px,100%)', boxSizing: 'border-box', maxHeight: '90vh', overflowY: 'auto', background: '#fff', padding: 22, borderRadius: 20 };
const close = { position: 'absolute', right: 12, top: 12, border: 0, borderRadius: 99, padding: 7, background: '#edf3f0', cursor: 'pointer' };
const label = { display: 'block', color: '#405a57', fontSize: 13, fontWeight: 800, margin: '14px 0 6px' };
const input = { display: 'block', width: '100%', boxSizing: 'border-box', marginTop: 6, border: '1px solid #cadbd4', borderRadius: 11, padding: 11, color: '#273b3e', font: 'inherit' };
