import React, { useEffect } from 'react';
import { ArrowRight, Heart, MessageCircle, ShieldCheck, Sparkles } from 'lucide-react';
import { Link } from 'react-router-dom';

export default function ChristianChatLanding() {
  useEffect(() => {
    const oldTitle = document.title;
    const description = document.querySelector('meta[name="description"]');
    const oldDescription = description?.content;
    document.title = 'Chat Cristão Online | Sala de Conversa Evangélica — Sigo com Fé';
    if (description) description.content = 'Entre na Sala de Conversa Cristã do Sigo com Fé: um espaço online de oração, Bíblia, amizade e esperança.';
    return () => { document.title = oldTitle; if (description && oldDescription) description.content = oldDescription; };
  }, []);

  const featureStyle = { background: '#fff', border: '1px solid #e0e6f5', borderRadius: 18, padding: 22, boxShadow: '0 8px 24px rgba(53,104,184,.08)' };
  return <main style={{ minHeight: '100vh', background: 'linear-gradient(180deg,#f5f8ff 0%,#fff 60%)', color: '#1e2240', padding: '20px 18px 56px' }}>
    <nav style={{ maxWidth: 1050, margin: '0 auto 55px', display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 14 }}><Link to="/" style={{ color: '#3568b8', fontWeight: 900, fontSize: '1.35rem', textDecoration: 'none' }}>Sigo com Fé</Link><div style={{ display: 'flex', gap: 10 }}><Link to="/login" style={{ textDecoration: 'none', color: '#3568b8', fontWeight: 700, padding: '10px 14px' }}>Entrar</Link><Link to="/register" style={{ textDecoration: 'none', background: '#3568b8', color: '#fff', borderRadius: 10, fontWeight: 700, padding: '10px 14px' }}>Criar conta</Link></div></nav>
    <section style={{ maxWidth: 850, margin: '0 auto', textAlign: 'center' }}><span style={{ display: 'inline-flex', alignItems: 'center', gap: 7, background: '#eaf2ff', color: '#3568b8', borderRadius: 999, padding: '8px 13px', fontWeight: 800, fontSize: 13 }}><MessageCircle size={16}/> Sala de Conversa Cristã</span><h1 style={{ margin: '18px 0 13px', fontSize: 'clamp(2.1rem,6vw,4.2rem)', lineHeight: 1.05 }}>Chat Cristão Online para falar de fé e esperança</h1><p style={{ maxWidth: 650, margin: '0 auto', color: '#59627d', fontSize: '1.14rem', lineHeight: 1.65 }}>Uma sala acolhedora para conversar, partilhar versículos e enviar pedidos de oração. A comunidade é gratuita e feita para caminhar junto.</p><div style={{ display: 'flex', justifyContent: 'center', gap: 12, flexWrap: 'wrap', marginTop: 28 }}><Link to="/register" style={{ display: 'inline-flex', alignItems: 'center', gap: 8, background: '#3568b8', borderRadius: 12, color: '#fff', padding: '14px 19px', textDecoration: 'none', fontWeight: 800 }}>Entrar na sala gratuitamente <ArrowRight size={18}/></Link><Link to="/comunidade-ao-vivo" style={{ display: 'inline-flex', alignItems: 'center', gap: 8, background: '#fff', border: '1px solid #cfd9ee', borderRadius: 12, color: '#3568b8', padding: '14px 19px', textDecoration: 'none', fontWeight: 800 }}>Conhecer a sala</Link></div></section>
    <section className="christian-chat-features" style={{ maxWidth: 920, margin: '56px auto 0', display: 'grid', gridTemplateColumns: 'repeat(3,minmax(0,1fr))', gap: 16 }}><article style={featureStyle}><Heart color="#c49a28"/><h2 style={{ fontSize: '1.05rem' }}>Pedidos de oração</h2><p style={{ color: '#667085', lineHeight: 1.55, marginBottom: 0 }}>Partilhe o que precisa e encontre pessoas para caminhar em oração.</p></article><article style={featureStyle}><ShieldCheck color="#3568b8"/><h2 style={{ fontSize: '1.05rem' }}>Conversa respeitosa</h2><p style={{ color: '#667085', lineHeight: 1.55, marginBottom: 0 }}>Um ambiente moderado, sem ofensas, spam ou exposição de dados pessoais.</p></article><article style={featureStyle}><Sparkles color="#6c3fa0"/><h2 style={{ fontSize: '1.05rem' }}>Fé no dia a dia</h2><p style={{ color: '#667085', lineHeight: 1.55, marginBottom: 0 }}>Versículos, encorajamento e amizades que ajudam a não caminhar sozinho.</p></article></section>
    <section style={{ maxWidth: 780, margin: '50px auto 0', background: '#1e3d6e', color: '#fff', borderRadius: 20, padding: '27px 30px', textAlign: 'center' }}><h2 style={{ marginTop: 0 }}>A sua voz tem lugar aqui</h2><p style={{ margin: '0 0 17px', opacity: .9, lineHeight: 1.55 }}>Crie a sua conta gratuita para escrever na sala e conhecer a comunidade Sigo com Fé.</p><Link to="/register" style={{ display: 'inline-block', background: '#f0c040', color: '#1e2240', borderRadius: 10, padding: '12px 17px', textDecoration: 'none', fontWeight: 900 }}>Criar conta grátis</Link></section>
    <style>{`@media(max-width:700px){.christian-chat-features{grid-template-columns:1fr !important}}`}</style>
  </main>;
}
