import React, { useEffect, useState } from 'react';
import { Check, Mail, Send, X } from 'lucide-react';
import { useAuth } from '../context/AuthContext';

const API = `${import.meta.env.VITE_API_URL || ''}/api/faith-vows`;
const card = { background: '#fffdf5', border: '1px solid #ead59a', borderRadius: 18, padding: 20, boxShadow: '0 8px 24px rgba(111,82,18,.10)', marginBottom: 14 };
const button = (background = '#6c47d4') => ({ background, color: '#fff', border: 'none', borderRadius: 10, padding: '11px 15px', fontWeight: 800, cursor: 'pointer', display: 'inline-flex', gap: 7, alignItems: 'center' });
const input = { width: '100%', boxSizing: 'border-box', border: '1px solid #d9d3bf', borderRadius: 10, padding: '11px 12px', font: 'inherit', marginBottom: 10 };

export default function FaithVows() {
  const { user, token } = useAuth();
  const isPastor = ['pastor', 'admin'].includes(user?.role);
  const [vows, setVows] = useState([]); const [memberCount, setMemberCount] = useState(0);
  const [form, setForm] = useState({ title: '', message: '', bible_verse: '', closes_at: '' });
  const [openEnvelope, setOpenEnvelope] = useState(null); const [amount, setAmount] = useState(''); const [notice, setNotice] = useState('');
  const headers = { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` };
  const load = async () => { const response = await fetch(`${API}${isPastor ? '/pastor/list' : '/mine'}`, { headers }); const data = await response.json(); setVows(data.vows || []); setMemberCount(data.member_count || 0); };
  useEffect(() => { if (token) load().catch(() => setNotice('Não foi possível carregar os Votos de Fé agora.')); }, [token]);
  const createVow = async (event) => { event.preventDefault(); setNotice(''); const response = await fetch(`${API}/pastor`, { method: 'POST', headers, body: JSON.stringify(form) }); const data = await response.json(); if (!response.ok) return setNotice(data.error || 'Não foi possível enviar o voto.'); setForm({ title: '', message: '', bible_verse: '', closes_at: '' }); setNotice(`Envelope enviado para ${data.recipients} membro(s).`); load(); };
  const respond = async (vow, status) => { setNotice(''); const response = await fetch(`${API}/${vow.id}/respond`, { method: 'POST', headers, body: JSON.stringify({ status, amount: status === 'accepted' ? amount : null }) }); const data = await response.json(); if (!response.ok) return setNotice(data.error || 'Não foi possível guardar a resposta.'); setOpenEnvelope(null); setAmount(''); setNotice(status === 'accepted' ? 'O teu Voto de Fé foi guardado. Obrigado por participar livremente.' : 'Resposta guardada. Podes participar noutro momento.'); load(); };
  const closeVow = async (id) => { await fetch(`${API}/pastor/${id}/close`, { method: 'POST', headers }); load(); };

  if (isPastor) return <main style={{ maxWidth: 850, margin: '0 auto', padding: '24px 16px' }}><header style={{ marginBottom: 18 }}><h1 style={{ margin: 0, color: '#3f286f' }}>✉️ Votos de Fé</h1><p style={{ color: '#5f6470', lineHeight: 1.5 }}>Cria envelopes para os membros da tua igreja. O valor é sempre escolhido livremente por cada pessoa.</p></header>{notice && <p style={{ ...card, color: notice.includes('Não') ? '#a23a20' : '#216b4f', padding: 12 }}>{notice}</p>}<form onSubmit={createVow} style={card}><h2 style={{ marginTop: 0, color: '#3f286f', fontSize: 18 }}>Novo Voto de Fé</h2><input required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} placeholder="Ex.: Voto do Livramento" style={input} /><textarea required value={form.message} onChange={(e) => setForm({ ...form, message: e.target.value })} placeholder="Escreve a mensagem espiritual para as famílias..." rows={4} style={{ ...input, resize: 'vertical' }} /><input value={form.bible_verse} onChange={(e) => setForm({ ...form, bible_verse: e.target.value })} placeholder="Versículo (opcional)" style={input} /><label style={{ fontSize: 13, color: '#5f6470' }}>Prazo opcional<input type="datetime-local" value={form.closes_at} onChange={(e) => setForm({ ...form, closes_at: e.target.value })} style={{ ...input, marginTop: 5 }} /></label><p style={{ fontSize: 12, color: '#65746b' }}>Não existe valor sugerido: cada família decide livremente conforme a sua possibilidade e fé.</p><button style={button()}><Send size={17}/> Enviar para {memberCount} membro(s)</button></form><h2 style={{ color: '#3f286f', fontSize: 18 }}>Campanhas enviadas</h2>{!vows.length ? <div style={card}>Ainda não enviaste nenhum voto.</div> : vows.map((vow) => <article key={vow.id} style={card}><div style={{ display: 'flex', justifyContent: 'space-between', gap: 12 }}><div><h3 style={{ margin: 0, color: '#51378c' }}>{vow.title}</h3><p style={{ marginBottom: 6 }}>{vow.message}</p>{vow.bible_verse && <i style={{ color: '#866b1c' }}>{vow.bible_verse}</i>}</div><span style={{ height: 25, fontSize: 12, fontWeight: 800, padding: '4px 8px', borderRadius: 999, background: vow.status === 'active' ? '#e3f5e8' : '#eee', color: '#216b4f' }}>{vow.status === 'active' ? 'ATIVO' : 'ENCERRADO'}</span></div><div style={{ display: 'flex', gap: 10, flexWrap: 'wrap', marginTop: 14, fontSize: 13 }}><b>✓ {vow.accepted_count || 0} aceitaram</b><span>— {vow.declined_count || 0} responderam depois</span><span>— Comprometido: R$ {Number(vow.pledged_total || 0).toFixed(2)}</span></div>{vow.status === 'active' && <button onClick={() => closeVow(vow.id)} style={{ ...button('#7c8682'), marginTop: 12 }}><X size={16}/> Encerrar voto</button>}</article>)}</main>;

  return <main style={{ maxWidth: 650, margin: '0 auto', padding: '24px 16px' }}><header style={{ textAlign: 'center', marginBottom: 18 }}><Mail size={36} color="#bd8a12"/><h1 style={{ color: '#3f286f', margin: '8px 0' }}>Os teus Votos de Fé</h1><p style={{ color: '#667085' }}>Cada envelope é pessoal. A resposta e o valor são livres e privados.</p></header>{notice && <p style={{ ...card, color: notice.includes('Não') ? '#a23a20' : '#216b4f', padding: 12 }}>{notice}</p>}{!vows.length ? <div style={{ ...card, textAlign: 'center' }}><Mail size={30} color="#bd8a12"/><p>Não tens nenhum envelope novo neste momento.</p></div> : vows.map((vow) => <article key={vow.id} style={{ ...card, background: 'linear-gradient(135deg,#fff9df,#fff)' }}><span style={{ fontSize: 12, fontWeight: 800, color: '#956b0d' }}>ENVELOPE DIGITAL · {vow.church_name}</span><h2 style={{ color: '#51378c', marginBottom: 8 }}>{vow.title}</h2><p style={{ lineHeight: 1.55 }}>{vow.message}</p>{vow.bible_verse && <blockquote style={{ margin: '14px 0', paddingLeft: 12, borderLeft: '3px solid #d4a21d', color: '#6e5a22' }}>{vow.bible_verse}</blockquote>}{vow.response_status ? <p style={{ color: vow.response_status === 'accepted' ? '#216b4f' : '#667085', fontWeight: 700 }}>{vow.response_status === 'accepted' ? `✓ Aceitaste este voto${vow.pledge_amount ? ` · R$ ${Number(vow.pledge_amount).toFixed(2)}` : ''}` : 'Respondeste: Agora não'}</p> : <button onClick={() => setOpenEnvelope(vow)} style={button('#bd8a12')}><Mail size={17}/> Abrir envelope</button>}</article>)}{openEnvelope && <div style={{ position: 'fixed', inset: 0, zIndex: 1200, background: 'rgba(24,16,35,.55)', display: 'grid', placeItems: 'center', padding: 16 }}><section style={{ ...card, width: 'min(100%, 460px)', margin: 0 }}><button onClick={() => setOpenEnvelope(null)} aria-label="Fechar" style={{ float: 'right', border: 0, background: 'transparent', cursor: 'pointer' }}><X/></button><span style={{ fontSize: 12, fontWeight: 800, color: '#956b0d' }}>VOTO DE FÉ</span><h2 style={{ color: '#51378c' }}>{openEnvelope.title}</h2><p>Olá, {user?.full_name || 'membro'}. Aceitas participar neste voto?</p><p style={{ fontSize: 13, color: '#65746b' }}>Se aceitares, podes indicar um valor livre ou deixar para decidir mais tarde. Não há obrigação.</p><label style={{ fontSize: 13, color: '#5f6470' }}>Valor que desejas comprometer (opcional)<input type="number" min="0" step="0.01" value={amount} onChange={(e) => setAmount(e.target.value)} placeholder="Decido conforme posso" style={{ ...input, marginTop: 5 }} /></label><div style={{ display: 'flex', gap: 9, marginTop: 14, flexWrap: 'wrap' }}><button onClick={() => respond(openEnvelope, 'accepted')} style={button('#257451')}><Check size={17}/> Aceito este voto</button><button onClick={() => respond(openEnvelope, 'declined')} style={button('#7c8682')}>Agora não</button></div></section></div>}</main>;
}
