import React, { useEffect, useRef, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { useAuth } from '../context/AuthContext';
import { ArrowLeft, Users, Lock, Globe, Image, Settings, Send, Share2, UserCheck, ShieldCheck, Video, X, FileText } from 'lucide-react';

const API = (import.meta.env.VITE_API_URL || '') + '/api';
const soft = { green:'#587b62', greenLight:'#edf4ed', gold:'#d9bd80', ink:'#33443a', border:'#dce8dd' };

export default function GroupDetail() {
  const { id } = useParams(); const navigate = useNavigate(); const { token, user } = useAuth(); const { t } = useTranslation();
  const [data, setData] = useState(null); const [error, setError] = useState(''); const [tab, setTab] = useState('posts');
  const [post, setPost] = useState(''); const [saving, setSaving] = useState(false); const [settings, setSettings] = useState(false);
  const [mediaFile, setMediaFile] = useState(null); const [mediaPreview, setMediaPreview] = useState(''); const mediaRef = useRef(null);
  const [tools, setTools] = useState({ prayers: [], events: [] }); const [prayer, setPrayer] = useState(''); const [eventTitle, setEventTitle] = useState(''); const [eventDate, setEventDate] = useState('');
  const load = async () => { try { const r = await fetch(`${API}/groups/${id}`, { headers:{ Authorization:`Bearer ${token}` } }); const body = await r.json(); if (!r.ok) { setError(body.error || 'Não foi possível abrir o grupo.'); if (body.group) setData({ group:body.group, members:[], posts:[], my_role:null, pending_requests:[] }); return; } setData(body); } catch { setError('Sem ligação ao servidor.'); } };
  useEffect(() => { load(); }, [id, token]);
  const loadTools = async () => { const r = await fetch(`${API}/groups/${id}/tools`, { headers:{ Authorization:`Bearer ${token}` } }); if (r.ok) setTools(await r.json()); };
  useEffect(() => { if (data?.my_role) loadTools().catch(() => {}); }, [id, token, data?.my_role]);
  const join = async () => { const r = await fetch(`${API}/groups/${id}/join`, { method:'POST', headers:{ 'Content-Type':'application/json', Authorization:`Bearer ${token}` }, body:'{}' }); const body=await r.json(); if (body.requested) setError('Pedido enviado ao administrador.'); else if (r.ok) load(); else setError(body.error || 'Não foi possível entrar.'); };
  const chooseMedia = (event) => { const file = event.target.files?.[0]; if (!file) return; if (!/^(image|video)\//.test(file.type)) { setError('Escolha uma foto ou vídeo.'); return; } if (file.size > 25 * 1024 * 1024) { setError('O ficheiro deve ter no máximo 25 MB.'); return; } setMediaFile(file); setMediaPreview(URL.createObjectURL(file)); };
  const clearMedia = () => { if (mediaPreview) URL.revokeObjectURL(mediaPreview); setMediaPreview(''); setMediaFile(null); if (mediaRef.current) mediaRef.current.value = ''; };
  const publish = async () => { if (!post.trim() && !mediaFile) return; setSaving(true); try { const form = new FormData(); form.append('content', post); if (mediaFile) form.append('media', mediaFile); const r=await fetch(`${API}/groups/${id}/posts`, {method:'POST',headers:{Authorization:`Bearer ${token}`},body:form}); const body=await r.json(); if (r.ok) { setData(d=>({...d,posts:[{...body.post,author_name:user.full_name,author_avatar:user.avatar_url},...d.posts]})); setPost(''); clearMedia(); } else setError(body.error || 'Não foi possível publicar.'); } finally { setSaving(false); } };
  const decide = async (userId, action) => { await fetch(`${API}/groups/${id}/requests/${userId}`, {method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({action})}); load(); };
  const saveSettings = async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const body={ description:form.get('description'), rules:form.get('rules'), privacy:form.get('privacy'), require_approval:form.get('require_approval')==='on' }; const r=await fetch(`${API}/groups/${id}/settings`, {method:'PATCH',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify(body)}); if (r.ok) { setSettings(false); load(); } };
  const sendPrayer = async () => { if (!prayer.trim()) return; const r=await fetch(`${API}/groups/${id}/prayers`, {method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({content:prayer})}); const body=await r.json(); if(r.ok){setTools(t=>({...t,prayers:[{...body.prayer,author_name:user.full_name},...t.prayers]}));setPrayer('');} };
  const createEvent = async () => { if (!eventTitle.trim() || !eventDate) return; const r=await fetch(`${API}/groups/${id}/events`, {method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({title:eventTitle,starts_at:eventDate})}); const body=await r.json(); if(r.ok){setTools(t=>({...t,events:[...t.events,body.event]}));setEventTitle('');setEventDate('');} };
  const invite = async () => { const url = `${window.location.origin}/grupos/${id}`; const text = `Venha participar do grupo "${data?.group?.name || 'Sigo com Fé'}" no Sigo com Fé: ${url}`; try { if (navigator.share) await navigator.share({ title: data?.group?.name || 'Sigo com Fé', text, url }); else { await navigator.clipboard.writeText(url); setError('Link do grupo copiado. Pode enviá-lo pelo WhatsApp ou por mensagem.'); } } catch (_) {} };
  if (!data) return <div style={{padding:40,textAlign:'center',color:'#667'}}>A carregar grupo...</div>;
  const { group, members=[], posts=[], my_role, pending_requests=[] } = data; const canManage=['admin','moderator'].includes(my_role);
  return <div style={{maxWidth:860,margin:'0 auto',padding:'16px 0 64px',color:soft.ink}}>
    <button onClick={()=>navigate('/grupos')} style={{border:0,background:'transparent',color:soft.green,display:'flex',gap:7,alignItems:'center',cursor:'pointer',fontWeight:700,margin:'0 0 14px'}}><ArrowLeft size={17}/> {t('groups.back')}</button>
    <section style={{borderRadius:22,overflow:'hidden',background:'#fff',border:`1px solid ${soft.border}`,boxShadow:'0 8px 24px rgba(45,75,55,.07)'}}>
      <div style={{height:150,background:group.cover_url?`linear-gradient(135deg,rgba(45,86,65,.48),rgba(179,151,99,.35)),url(${group.cover_url}) center/cover`:'linear-gradient(135deg,#63836a,#9db093)',display:'flex',alignItems:'end',padding:22,color:'#fff'}}>
        <div><div style={{fontSize:12,fontWeight:800,letterSpacing:'.08em',textTransform:'uppercase',opacity:.88}}>{group.privacy==='private' ? <><Lock size={12} style={{verticalAlign:'-2px'}}/> {t('groups.private')}</> : <><Globe size={12} style={{verticalAlign:'-2px'}}/> {t('groups.public')}</>}</div><h1 style={{margin:'5px 0 0',fontSize:28}}>{group.name}</h1></div>
      </div>
      <div style={{padding:'18px 22px'}}><p style={{margin:'0 0 14px',lineHeight:1.6,color:'#617066'}}>{group.description || 'Uma comunidade para crescer na fé em conjunto.'}</p>
        <div style={{display:'flex',gap:10,flexWrap:'wrap',alignItems:'center'}}><span style={{fontSize:13,display:'flex',gap:5,alignItems:'center'}}><Users size={15}/>{members.length || group.member_count || 0} {t('groups.members')}</span><span style={{fontSize:13}}>Criado por {group.creator_name || 'a comunidade'}</span>
          {!my_role && <button onClick={join} style={{marginLeft:'auto',border:0,borderRadius:12,padding:'10px 16px',background:soft.green,color:'#fff',fontWeight:800,cursor:'pointer'}}>{group.privacy==='private' || group.require_approval ? t('groups.join') : t('groups.joinGroup')}</button>}
          {my_role && <button onClick={invite} style={{marginLeft:'auto',border:`1px solid ${soft.border}`,borderRadius:12,padding:'9px 13px',background:'#fff',color:soft.green,fontWeight:700,cursor:'pointer',display:'flex',gap:6,alignItems:'center'}}><Share2 size={16}/> Convidar</button>}
          {canManage && <button onClick={()=>setSettings(true)} style={{border:`1px solid ${soft.border}`,borderRadius:12,padding:'9px 13px',background:'#fff',color:soft.green,fontWeight:700,cursor:'pointer',display:'flex',gap:6,alignItems:'center'}}><Settings size={16}/> Gerir grupo</button>}
        </div>
      </div>
    </section>
    {error && <div style={{marginTop:14,padding:12,borderRadius:12,background:'#fff7e7',color:'#806536',fontSize:13}}>{error}</div>}
    {my_role && <nav style={{display:'flex',gap:8,margin:'20px 0 14px',borderBottom:`1px solid ${soft.border}`,paddingBottom:10,flexWrap:'wrap'}}>{[['posts','Publicações'],['members','Membros'],['tools','Oração e agenda'],['about','Sobre']].map(([key,label])=><button key={key} onClick={()=>setTab(key)} style={{border:0,borderRadius:20,padding:'8px 14px',background:tab===key?soft.greenLight:'transparent',color:tab===key?soft.green:'#68766b',fontWeight:800,cursor:'pointer'}}>{label}</button>)}</nav>}
    {!my_role ? <div style={{marginTop:20,padding:28,textAlign:'center',background:'#fffdf7',border:`1px solid ${soft.border}`,borderRadius:18}}><Lock size={30} color={soft.green}/><h2 style={{fontSize:18}}>Este é um espaço da comunidade</h2><p style={{color:'#69786c'}}>Entre no grupo para ver publicações, membros e ferramentas.</p></div> : <>
      {tab==='posts' && <><div style={{background:'#fff',padding:16,borderRadius:18,border:`1px solid ${soft.border}`,marginBottom:14}}><textarea value={post} onChange={e=>setPost(e.target.value)} rows={3} placeholder={t('groups.writePlaceholder')} style={{width:'100%',border:`1px solid ${soft.border}`,borderRadius:12,padding:12,resize:'vertical',boxSizing:'border-box',font:'inherit'}}/><input ref={mediaRef} onChange={chooseMedia} type="file" accept="image/*,video/*" style={{display:'none'}}/>{mediaPreview&&<div style={{position:'relative',marginTop:10,borderRadius:12,overflow:'hidden',border:`1px solid ${soft.border}`}}>{mediaFile?.type.startsWith('video/')?<video src={mediaPreview} controls style={{display:'block',width:'100%',maxHeight:300,background:'#102018'}}/>:<img src={mediaPreview} alt="Pré-visualização" style={{display:'block',width:'100%',maxHeight:300,objectFit:'cover'}}/>}<button type="button" onClick={clearMedia} aria-label="Remover ficheiro" style={{position:'absolute',top:8,right:8,width:30,height:30,border:0,borderRadius:'50%',background:'rgba(20,35,27,.75)',color:'#fff',display:'grid',placeItems:'center',cursor:'pointer'}}><X size={17}/></button></div>}<div style={{marginTop:10,display:'flex',gap:8,alignItems:'center',flexWrap:'wrap'}}><button type="button" onClick={()=>mediaRef.current?.click()} style={{display:'flex',alignItems:'center',gap:6,border:`1px solid ${soft.border}`,borderRadius:10,padding:'8px 11px',background:'#fff',color:soft.green,fontWeight:800,cursor:'pointer'}}>{mediaFile?.type.startsWith('video/')?<Video size={16}/>:<Image size={16}/>} {mediaFile ? 'Trocar ficheiro' : 'Foto ou vídeo'}</button><button disabled={saving||(!post.trim()&&!mediaFile)} onClick={publish} style={{marginLeft:'auto',display:'flex',alignItems:'center',gap:6,border:0,borderRadius:10,padding:'9px 14px',background:soft.green,color:'#fff',fontWeight:800,cursor:'pointer',opacity:(saving||(!post.trim()&&!mediaFile))?.6:1}}><Send size={15}/>{saving?'A publicar...':'Publicar'}</button></div></div>
        {posts.length===0 ? <div style={{padding:32,textAlign:'center',background:'#fff',borderRadius:18,border:`1px solid ${soft.border}`}}>{t('groups.noPosts')}</div> : posts.map(p=>{const isVideo=/\/video\/upload\/|\.(mp4|webm|mov)(\?|$)/i.test(p.media_url||''); return <article key={p.id} style={{background:'#fff',borderRadius:18,border:`1px solid ${soft.border}`,padding:18,marginBottom:12}}><div style={{fontWeight:800,fontSize:14}}>{p.author_name}</div><div style={{fontSize:12,color:'#849087',margin:'3px 0 12px'}}>{new Date(p.created_at).toLocaleString()}</div>{p.content&&<p style={{whiteSpace:'pre-wrap',lineHeight:1.6,margin:0}}>{p.content}</p>}{p.media_url&&(isVideo?<video src={p.media_url} controls preload="metadata" style={{width:'100%',borderRadius:12,marginTop:12,maxHeight:440,background:'#102018'}}/>:<img src={p.media_url} alt="Publicação do grupo" style={{width:'100%',borderRadius:12,marginTop:12,maxHeight:440,objectFit:'cover'}}/>)}</article>})}</>}
      {tab==='members' && <div style={{background:'#fff',borderRadius:18,border:`1px solid ${soft.border}`,padding:12}}>{members.map(m=><div key={m.id} style={{display:'flex',alignItems:'center',gap:10,padding:'10px 6px',borderBottom:`1px solid #edf2ed`}}><div style={{width:36,height:36,borderRadius:'50%',background:'#e7efe7',display:'grid',placeItems:'center',fontWeight:800}}>{m.avatar_url?<img src={m.avatar_url} alt="" style={{width:'100%',height:'100%',borderRadius:'50%',objectFit:'cover'}}/>:m.full_name?.[0]}</div><span style={{fontWeight:700,flex:1}}>{m.full_name}</span><span style={{fontSize:12,color:soft.green,fontWeight:800}}>{m.role==='admin'?'Criador / Admin':m.role==='moderator'?'Moderador':'Membro'}</span></div>)}</div>}
      {tab==='tools' && <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:14}}><section style={{background:'#fff',borderRadius:18,border:`1px solid ${soft.border}`,padding:18}}><h3 style={{marginTop:0}}>🙏 Pedidos de oração</h3><textarea value={prayer} onChange={e=>setPrayer(e.target.value)} rows={3} placeholder="Como podemos orar por você?" style={{width:'100%',boxSizing:'border-box',padding:10,border:`1px solid ${soft.border}`,borderRadius:10}}/><button onClick={sendPrayer} style={{marginTop:8,border:0,borderRadius:9,padding:'8px 12px',background:soft.green,color:'#fff',fontWeight:800,cursor:'pointer'}}>Enviar pedido</button>{tools.prayers.map(p=><div key={p.id} style={{padding:'10px 0',borderTop:'1px solid #edf2ed',marginTop:8,fontSize:13}}><b>{p.author_name}</b><br/>{p.content}</div>)}</section><section style={{background:'#fff',borderRadius:18,border:`1px solid ${soft.border}`,padding:18}}><h3 style={{marginTop:0}}>📅 Agenda do grupo</h3>{canManage&&<><input value={eventTitle} onChange={e=>setEventTitle(e.target.value)} placeholder="Nome do evento" style={{width:'100%',boxSizing:'border-box',padding:10,border:`1px solid ${soft.border}`,borderRadius:10,marginBottom:8}}/><input type="datetime-local" value={eventDate} onChange={e=>setEventDate(e.target.value)} style={{width:'100%',boxSizing:'border-box',padding:10,border:`1px solid ${soft.border}`,borderRadius:10}}/><button onClick={createEvent} style={{marginTop:8,border:0,borderRadius:9,padding:'8px 12px',background:soft.green,color:'#fff',fontWeight:800,cursor:'pointer'}}>Criar evento</button></>}{tools.events.length===0?<p style={{fontSize:13,color:'#758176'}}>Nenhum evento marcado.</p>:tools.events.map(e=><div key={e.id} style={{padding:'10px 0',borderTop:'1px solid #edf2ed'}}><b>{e.title}</b><br/><span style={{fontSize:12}}>{new Date(e.starts_at).toLocaleString()}</span></div>)}</section></div>}
      {tab==='about' && <div style={{background:'#fff',borderRadius:18,border:`1px solid ${soft.border}`,padding:20}}><h3 style={{marginTop:0,display:'flex',gap:7,alignItems:'center'}}><FileText size={18} color={soft.green}/> Regras do grupo</h3><p style={{whiteSpace:'pre-wrap',lineHeight:1.7,color:'#59695d'}}>{group.rules || 'Respeite cada pessoa, publique com amor e mantenha este espaço seguro e edificante.'}</p></div>}
      {canManage && pending_requests.length>0 && <section style={{marginTop:18,background:'#fffdf7',border:'1px solid #ead9ae',borderRadius:18,padding:18}}><h3 style={{margin:'0 0 10px',fontSize:16,display:'flex',gap:7,alignItems:'center'}}><UserCheck size={18} color="#9a763e"/> Pedidos para entrar ({pending_requests.length})</h3>{pending_requests.map(r=><div key={r.user_id} style={{display:'flex',alignItems:'center',gap:10,padding:'9px 0'}}><span style={{fontWeight:700,flex:1}}>{r.full_name}</span><button onClick={()=>decide(r.user_id,'decline')} style={{border:0,background:'transparent',color:'#a46a57',cursor:'pointer'}}>Recusar</button><button onClick={()=>decide(r.user_id,'approve')} style={{border:0,borderRadius:9,background:soft.green,color:'#fff',padding:'7px 10px',fontWeight:800,cursor:'pointer'}}>Aprovar</button></div>)}</section>}
    </>}
    {settings && <div style={{position:'fixed',inset:0,zIndex:1500,background:'rgba(27,45,35,.42)',display:'grid',placeItems:'center',padding:16}}><form onSubmit={saveSettings} style={{width:'min(480px,100%)',background:'#fff',borderRadius:20,padding:22}}><h2 style={{marginTop:0,fontSize:19,display:'flex',gap:7,alignItems:'center'}}><ShieldCheck size={20} color={soft.green}/> Gestão e privacidade</h2><label style={{fontSize:13,fontWeight:700}}>Descrição<textarea name="description" defaultValue={group.description||''} rows={3} style={{display:'block',width:'100%',marginTop:5,padding:10,border:`1px solid ${soft.border}`,borderRadius:10,boxSizing:'border-box',font:'inherit'}}/></label><label style={{fontSize:13,fontWeight:700,display:'block',marginTop:12}}>Privacidade<select name="privacy" defaultValue={group.privacy} style={{display:'block',width:'100%',marginTop:5,padding:10,border:`1px solid ${soft.border}`,borderRadius:10}}><option value="public">Público — qualquer pessoa pode descobrir</option><option value="private">Privado — apenas membros veem o conteúdo</option></select></label><label style={{display:'flex',gap:8,marginTop:12,fontSize:13}}><input name="require_approval" type="checkbox" defaultChecked={group.require_approval}/> Aprovar novos membros antes de entrarem</label><label style={{fontSize:13,fontWeight:700,display:'block',marginTop:12}}>Regras<textarea name="rules" defaultValue={group.rules||''} rows={4} placeholder="Ex.: respeito, oração, sem publicidade..." style={{display:'block',width:'100%',marginTop:5,padding:10,border:`1px solid ${soft.border}`,borderRadius:10,boxSizing:'border-box',font:'inherit'}}/></label><div style={{display:'flex',justifyContent:'end',gap:8,marginTop:18}}><button type="button" onClick={()=>setSettings(false)} style={{border:0,background:'transparent',padding:10,cursor:'pointer'}}>Cancelar</button><button style={{border:0,borderRadius:10,background:soft.green,color:'#fff',padding:'10px 14px',fontWeight:800,cursor:'pointer'}}>Guardar</button></div></form></div>}
  </div>;
}
