import React from 'react';
import { Link } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { useAuth } from '../context/AuthContext';

const icons = ['🌱','📰','🙏','📖','⚔️','🤝','🏠','🛡️'];
const make = (heading,intro,create,wall,all,ready,free,sections) => ({ heading,intro,create,wall,all,ready,free,sections });
const copy = {
 pt: make('Conheça o Sigo com Fé','Uma comunidade cristã para orar, aprender a Bíblia, fazer amizades, partilhar a fé e jogar em família.','Criar conta grátis','Ir para o Mural','Ver todas as funções','Pronto para fazer parte?','A conta é gratuita e fica pronta em poucos minutos.',[['Crie a sua conta gratuita','Crie a conta, complete o perfil e escolha o idioma.'],['Mural da Comunidade','Publique testemunhos, versículos, reflexões, louvores, fotos e vídeos.'],['Oração, fé e apoio','Partilhe pedidos de oração, ore por outras pessoas e participe nas jornadas de fé.'],['Bíblia e crescimento espiritual','Leia a Palavra, reflexões, trilhas de sabedoria e desafios diários.'],['Jogos bíblicos','No Duelo Bíblico desafie uma pessoa real. Visitantes jogam três minutos; a conta guarda progresso e ranking.'],['Pessoas, amigos e mensagens','Conheça membros, faça amizades e converse em privado com respeito.'],['Comunidade e serviços','Descubra grupos, igrejas, música, eventos e transmissões.'],['Segurança e controlo','A conta é pessoal. Use uma senha segura e recupere-a em “Esqueci a minha senha”.']]),
 es: make('Conoce Sigo com Fé','Una comunidad cristiana para orar, aprender la Biblia, hacer amistades, compartir la fe y jugar en familia.','Crear cuenta gratis','Ir al Mural','Ver todas las funciones','¿Listo para formar parte?','La cuenta es gratis y estará lista en pocos minutos.',[['Crea tu cuenta gratis','Crea la cuenta, completa el perfil y elige el idioma.'],['Mural de la Comunidad','Publica testimonios, versículos, reflexiones, alabanzas, fotos y vídeos.'],['Oración, fe y apoyo','Comparte peticiones de oración, ora por otros y participa en jornadas de fe.'],['Biblia y crecimiento espiritual','Lee la Palabra, reflexiones, senderos de sabiduría y desafíos diarios.'],['Juegos bíblicos','En el Duelo Bíblico desafía a una persona real. Los visitantes juegan tres minutos; la cuenta guarda progreso y ranking.'],['Personas, amigos y mensajes','Conoce miembros, haz amistades y conversa en privado con respeto.'],['Comunidad y servicios','Descubre grupos, iglesias, música, eventos y transmisiones.'],['Seguridad y control','La cuenta es personal. Usa una contraseña segura y recupérala en “Olvidé mi contraseña”.']]),
 en: make('Discover Sigo com Fé','A Christian community to pray, learn the Bible, make friends, share faith and play as a family.','Create free account','Go to Wall','See all features','Ready to join?','Your free account will be ready in a few minutes.',[['Create your free account','Create your account, complete your profile and choose a language.'],['Community Wall','Share testimonies, verses, reflections, worship, photos and videos.'],['Prayer, faith and support','Share prayer requests, pray for others and join faith journeys.'],['Bible and spiritual growth','Read the Word, reflections, wisdom trails and daily challenges.'],['Bible games','In Bible Duel, challenge a real person. Visitors play for three minutes; an account saves progress and ranking.'],['People, friends and messages','Meet members, make friends and chat privately with respect.'],['Community and services','Discover groups, churches, music, events and broadcasts.'],['Safety and control','Your account is personal. Use a strong password and recover it with “Forgot password”.']]),
 de: make('Lerne Sigo com Fé kennen','Eine christliche Gemeinschaft zum Beten, Bibellernen, Freunde finden, Glauben teilen und Spielen mit der Familie.','Kostenloses Konto erstellen','Zur Pinnwand','Alle Funktionen ansehen','Bereit dabei zu sein?','Das kostenlose Konto ist in wenigen Minuten fertig.',[['Kostenloses Konto erstellen','Erstelle dein Konto, vervollständige das Profil und wähle die Sprache.'],['Gemeinschaftspinnwand','Teile Zeugnisse, Verse, Gedanken, Lobpreis, Fotos und Videos.'],['Gebet, Glaube und Unterstützung','Teile Gebetsanliegen, bete für andere und nimm an Glaubenswegen teil.'],['Bibel und geistliches Wachstum','Lies das Wort, Andachten, Weisheitswege und tägliche Herausforderungen.'],['Bibelspiele','Im Bibelduell forderst du echte Personen heraus. Gäste spielen drei Minuten; ein Konto speichert Fortschritt und Rangliste.'],['Menschen, Freunde und Nachrichten','Lerne Mitglieder kennen, finde Freunde und schreibe privat mit Respekt.'],['Gemeinschaft und Angebote','Entdecke Gruppen, Kirchen, Musik, Veranstaltungen und Übertragungen.'],['Sicherheit und Kontrolle','Dein Konto ist persönlich. Nutze ein sicheres Passwort und „Passwort vergessen“.']]),
 fr: make('Découvrir Sigo com Fé','Une communauté chrétienne pour prier, apprendre la Bible, se faire des amis, partager la foi et jouer en famille.','Créer un compte gratuit','Aller au Mur','Voir toutes les fonctions','Prêt à nous rejoindre ?','Le compte gratuit est prêt en quelques minutes.',[['Créez votre compte gratuit','Créez votre compte, complétez le profil et choisissez votre langue.'],['Mur de la communauté','Publiez témoignages, versets, réflexions, louanges, photos et vidéos.'],['Prière, foi et soutien','Partagez des demandes de prière, priez pour les autres et rejoignez les parcours de foi.'],['Bible et croissance spirituelle','Lisez la Parole, les réflexions, parcours de sagesse et défis quotidiens.'],['Jeux bibliques','Dans le Duel Biblique, défiez une vraie personne. Les visiteurs jouent trois minutes ; le compte garde le progrès et le classement.'],['Personnes, amis et messages','Rencontrez des membres, faites des amis et discutez en privé avec respect.'],['Communauté et services','Découvrez groupes, églises, musique, événements et diffusions.'],['Sécurité et contrôle','Votre compte est personnel. Utilisez un mot de passe sûr et « Mot de passe oublié ».']]),
 ro: make('Descoperă Sigo com Fé','O comunitate creștină pentru rugăciune, studiu biblic, prietenii, împărtășirea credinței și jocuri în familie.','Creează cont gratuit','Mergi la Perete','Vezi toate funcțiile','Gata să faci parte?','Contul gratuit este gata în câteva minute.',[['Creează un cont gratuit','Creează contul, completează profilul și alege limba.'],['Peretele comunității','Publică mărturii, versete, reflecții, laudă, fotografii și videoclipuri.'],['Rugăciune, credință și sprijin','Împărtășește cereri de rugăciune, roagă-te pentru alții și participă la călătorii de credință.'],['Biblia și creșterea spirituală','Citește Cuvântul, reflecții, trasee de înțelepciune și provocări zilnice.'],['Jocuri biblice','În Duel Biblic provoacă o persoană reală. Vizitatorii joacă trei minute; contul salvează progresul și clasamentul.'],['Oameni, prieteni și mesaje','Cunoaște membri, fă prieteni și discută privat cu respect.'],['Comunitate și servicii','Descoperă grupuri, biserici, muzică, evenimente și transmisiuni.'],['Siguranță și control','Contul este personal. Folosește o parolă sigură și „Am uitat parola”.']]),
 ru: make('Познакомьтесь с Sigo com Fé','Христианское сообщество для молитвы, изучения Библии, дружбы, общения о вере и семейных игр.','Создать бесплатный аккаунт','Перейти к Стене','Все функции','Готовы присоединиться?','Бесплатный аккаунт будет готов через несколько минут.',[['Создайте бесплатный аккаунт','Создайте аккаунт, заполните профиль и выберите язык.'],['Стена сообщества','Публикуйте свидетельства, стихи, размышления, прославление, фото и видео.'],['Молитва, вера и поддержка','Делитесь молитвенными просьбами, молитесь за других и участвуйте в путях веры.'],['Библия и духовный рост','Читайте Слово, размышления, пути мудрости и ежедневные задания.'],['Библейские игры','В Библейской дуэли вызовите реального человека. Гости играют три минуты; аккаунт сохраняет прогресс и рейтинг.'],['Люди, друзья и сообщения','Знакомьтесь с участниками, находите друзей и общайтесь лично с уважением.'],['Сообщество и сервисы','Откройте группы, церкви, музыку, события и трансляции.'],['Безопасность и контроль','Ваш аккаунт личный. Используйте надёжный пароль и «Забыли пароль?».']]),
};

export default function GuiaSigoComFe() {
  const { user } = useAuth(); const { i18n } = useTranslation();
  const c = copy[(i18n.language || 'pt').slice(0,2)] || copy.pt; const actionTo = user ? '/' : '/register'; const action = user ? c.wall : c.create;
  return <main style={{minHeight:'100vh',padding:'clamp(18px,4vw,48px) 16px 56px',background:'linear-gradient(145deg,#f5f8ff,#f9fbf5)'}}><div style={{maxWidth:950,margin:'0 auto'}}><header style={{padding:'clamp(24px,5vw,46px)',borderRadius:26,color:'#fff',background:'linear-gradient(135deg,#2f6652,#709b72)'}}><b style={{color:'#fff0a6'}}>GUIA COMPLETO</b><h1>{c.heading}</h1><p>{c.intro}</p><div style={{display:'flex',gap:10,flexWrap:'wrap',marginTop:22}}><Link to={actionTo} style={{padding:'12px 18px',borderRadius:12,background:'#fff5c7',color:'#5d4a19',textDecoration:'none',fontWeight:900}}>{action}</Link><a href="#funcoes" style={{padding:'12px 18px',borderRadius:12,border:'1px solid rgba(255,255,255,.5)',color:'#fff',textDecoration:'none'}}>{c.all}</a></div></header><section id="funcoes" style={{marginTop:24,display:'grid',gap:14}}>{c.sections.map(([title,text],i)=><article key={title} style={{display:'grid',gridTemplateColumns:'48px minmax(0,1fr)',gap:15,padding:20,borderRadius:18,background:'#fff',border:'1px solid #e2ebe2'}}><div style={{display:'grid',placeItems:'center',width:48,height:48,borderRadius:14,background:'#edf6ee',fontSize:24}}>{icons[i]}</div><div><h2 style={{margin:'1px 0 8px',color:'#274c3c',fontSize:20}}>{title}</h2><p style={{margin:0,color:'#586a60',lineHeight:1.55}}>{text}</p></div></article>)}</section><footer style={{marginTop:24,padding:'28px 20px',borderRadius:20,textAlign:'center',color:'#fff',background:'#563787'}}><h2>{c.ready}</h2><p>{c.free}</p><Link to={actionTo} style={{display:'inline-block',padding:'12px 20px',borderRadius:12,background:'#fff',color:'#563787',textDecoration:'none',fontWeight:900}}>{action}</Link></footer></div></main>;
}
