import React, { useMemo, useState } from 'react';
import { BookOpen, CheckCircle2, ChevronRight, LockKeyhole, Medal, Sparkles } from 'lucide-react';
import { useTranslation } from 'react-i18next';

const bi = (pt, es) => ({ pt, es });
const TRAILS = [
  { id:'paz', emoji:'🕊️', color:'#4c8d79', title:bi('Paz para o coração','Paz para el corazón'), sub:bi('Para respirar, confiar e descansar em Deus.','Para respirar, confiar y descansar en Dios.'),
    practice:[bi('Respire fundo três vezes e entregue esta preocupação a Deus.','Respira profundo tres veces y entrega esta preocupación a Dios.'),bi('Escreva uma verdade da Palavra para lembrar hoje.','Escribe una verdad de la Palabra para recordar hoy.'),bi('Faça uma pausa de cinco minutos sem telas para orar.','Haz una pausa de cinco minutos sin pantallas para orar.'),bi('Agradeça a Deus por uma pequena coisa do seu dia.','Agradece a Dios por una cosa pequeña de tu día.'),bi('Envie uma mensagem de paz para alguém querido.','Envía un mensaje de paz a alguien querido.'),bi('Escolha uma atitude calma para praticar hoje.','Elige una actitud tranquila para practicar hoy.')],
    lessons:[
      [bi('Entregue o caminho','Entrega el camino'),bi('“Confia no Senhor de todo o teu coração.” — Provérbios 3:5','“Confía en el Señor con todo tu corazón.” — Proverbios 3:5'),bi('Nem tudo precisa ser resolvido hoje. Entregue a Deus o que pesa no seu coração.','No todo necesita resolverse hoy. Entrega a Dios lo que pesa en tu corazón.')],
      [bi('Cuide dos pensamentos','Cuida tus pensamientos'),bi('“Guarda o teu coração.” — Provérbios 4:23','“Guarda tu corazón.” — Proverbios 4:23'),bi('A paz cresce quando escolhemos o que alimenta os nossos pensamentos.','La paz crece cuando elegimos lo que alimenta nuestros pensamientos.')],
      [bi('Caminhe com calma','Camina con calma'),bi('“O Senhor lhe dirige os passos.” — Provérbios 16:9','“El Señor dirige sus pasos.” — Proverbios 16:9'),bi('Você pode dar o próximo passo sem enxergar toda a estrada.','Puedes dar el siguiente paso sin ver todo el camino.')],
    ] },
  { id:'sabedoria', emoji:'💡', color:'#b57920', title:bi('Sabedoria no dia a dia','Sabiduría para cada día'), sub:bi('Decisões simples guiadas pela Palavra de Deus.','Decisiones sencillas guiadas por la Palabra de Dios.'),
    practice:[bi('Antes de decidir, faça uma oração curta pedindo clareza.','Antes de decidir, haz una oración breve pidiendo claridad.'),bi('Ouça até o fim antes de responder em uma conversa.','Escucha hasta el final antes de responder en una conversación.'),bi('Faça uma bondade simples sem esperar retorno.','Haz una bondad sencilla sin esperar nada a cambio.'),bi('Peça conselho a uma pessoa sábia e de confiança.','Pide consejo a una persona sabia y de confianza.'),bi('Troque uma resposta apressada por uma resposta gentil.','Cambia una respuesta apresurada por una respuesta amable.'),bi('Anote uma decisão e entregue-a a Deus em oração.','Anota una decisión y entrégala a Dios en oración.')],
    lessons:[
      [bi('Peça sabedoria','Pide sabiduría'),bi('“O temor do Senhor é o princípio da sabedoria.” — Provérbios 9:10','“El temor del Señor es el principio de la sabiduría.” — Proverbios 9:10'),bi('Sabedoria não é saber tudo. É reconhecer que Deus vê o que nós não vemos.','La sabiduría no es saberlo todo. Es reconocer que Dios ve lo que nosotros no vemos.')],
      [bi('Ouça antes de falar','Escucha antes de hablar'),bi('“Pronto para ouvir, tardio para falar.” — Tiago 1:19','“Pronto para oír, tardo para hablar.” — Santiago 1:19'),bi('Uma resposta paciente pode cuidar de uma amizade, uma família e um coração.','Una respuesta paciente puede cuidar una amistad, una familia y un corazón.')],
      [bi('Faça o bem possível','Haz el bien posible'),bi('“Não deixes de fazer bem.” — Provérbios 3:27','“No te niegues a hacer el bien.” — Proverbios 3:27'),bi('A sabedoria aparece em escolhas pequenas: ajudar, perdoar e agir com honestidade.','La sabiduría aparece en decisiones pequeñas: ayudar, perdonar y actuar con honestidad.')],
    ] },
  { id:'familia', emoji:'🏠', color:'#7755aa', title:bi('Família e perdão','Familia y perdón'), sub:bi('Palavras que aproximam e atitudes que restauram.','Palabras que acercan y actitudes que restauran.'),
    practice:[bi('Use uma frase gentil em uma conversa hoje.','Usa una frase amable en una conversación hoy.'),bi('Ore por alguém que você precisa entregar a Deus.','Ora por alguien que necesitas entregar a Dios.'),bi('Agradeça a alguém da sua família por algo simples.','Agradece a alguien de tu familia por algo sencillo.'),bi('Peça perdão por uma palavra que poderia ser melhor.','Pide perdón por una palabra que pudo ser mejor.'),bi('Faça um gesto de carinho sem motivo especial.','Haz un gesto de cariño sin un motivo especial.'),bi('Escolha ouvir com calma uma pessoa da sua casa.','Elige escuchar con calma a una persona de tu hogar.')],
    lessons:[
      [bi('Palavras que acalmam','Palabras que calman'),bi('“A resposta branda desvia o furor.” — Provérbios 15:1','“La blanda respuesta quita la ira.” — Proverbios 15:1'),bi('A bondade pode abrir espaço para a paz mesmo numa conversa difícil.','La bondad puede abrir espacio para la paz incluso en una conversación difícil.')],
      [bi('Escolha o perdão','Elige el perdón'),bi('“O amor cobre todas as transgressões.” — Provérbios 10:12','“El amor cubrirá todas las faltas.” — Proverbios 10:12'),bi('Perdoar não apaga o que aconteceu, mas impede a dor de mandar no coração.','Perdonar no borra lo ocurrido, pero evita que el dolor gobierne el corazón.')],
      [bi('Construa o lar','Construye tu hogar'),bi('“Com a sabedoria se edifica a casa.” — Provérbios 24:3','“Con sabiduría se edificará la casa.” — Proverbios 24:3'),bi('O lar é fortalecido por presença, paciência e pequenas demonstrações de amor.','El hogar se fortalece con presencia, paciencia y pequeñas muestras de amor.')],
    ] },
];

const COPY={pt:{eyebrow:'SABEDORIA PARA A VIDA',page:'Trilhas de Sabedoria',intro:'Uma caminhada que continua com você: novos níveis, práticas diferentes e passos simples com a Palavra de Deus.',steps:'passos concluídos',level:'Nível',medal:'Medalha conquistada!',medalText:'Você concluiu este nível. Continue para aprofundar a sua caminhada.',step:'PASSO',practice:'Prática de hoje:',finish:'Concluir este passo',locked:'Conclua o passo anterior para liberar este.',continue:'Começar o próximo nível',saved:'Seu progresso fica guardado neste aparelho.'},es:{eyebrow:'SABIDURÍA PARA LA VIDA',page:'Rutas de Sabiduría',intro:'Un camino que continúa contigo: nuevos niveles, prácticas diferentes y pasos sencillos con la Palabra de Dios.',steps:'pasos completados',level:'Nivel',medal:'¡Medalla conseguida!',medalText:'Completaste este nivel. Continúa para profundizar tu camino.',step:'PASO',practice:'Práctica de hoy:',finish:'Completar este paso',locked:'Completa el paso anterior para desbloquearlo.',continue:'Comenzar el siguiente nivel',saved:'Tu progreso se guarda en este dispositivo.'}};
const STORAGE='sigo_wisdom_trails_v3';

export default function WisdomTrails(){
  const {i18n}=useTranslation(); const lang=(i18n.language||'pt').startsWith('es')?'es':'pt'; const c=COPY[lang];
  const [activeId,setActiveId]=useState(TRAILS[0].id);
  const [progress,setProgress]=useState(()=>{try{return JSON.parse(localStorage.getItem(STORAGE))||{}}catch(_){return {}}});
  const active=TRAILS.find(item=>item.id===activeId)||TRAILS[0]; const state=progress[active.id]||{level:1,done:[]}; const finished=state.done.length===3;
  const total=useMemo(()=>Object.values(progress).reduce((sum,item)=>sum+(item.done?.length||0),0),[progress]);
  const save=updater=>setProgress(old=>{const next=updater(old);localStorage.setItem(STORAGE,JSON.stringify(next));return next});
  const complete=index=>save(old=>({...old,[active.id]:{...state,done:[...new Set([...state.done,index])]}}));
  const nextLevel=()=>save(old=>({...old,[active.id]:{level:state.level+1,done:[]}}));
  const practice=index=>active.practice[((state.level-1)*3+index)%active.practice.length][lang];
  return <div style={{maxWidth:920,margin:'0 auto',padding:'8px 0 34px',color:'#243c38'}}>
    <section style={{borderRadius:22,padding:'28px clamp(20px,4vw,42px)',color:'white',background:'linear-gradient(125deg,#244f43,#477b6a 58%,#a68236)',boxShadow:'0 16px 32px rgba(30,74,61,.2)'}}><div style={{display:'flex',justifyContent:'space-between',gap:18,alignItems:'flex-start',flexWrap:'wrap'}}><div><span style={{display:'inline-flex',gap:7,alignItems:'center',padding:'6px 10px',borderRadius:99,background:'rgba(255,255,255,.16)',fontSize:12,fontWeight:800}}><Sparkles size={14}/>{c.eyebrow}</span><h1 style={{fontSize:'clamp(28px,4vw,42px)',margin:'14px 0 8px',lineHeight:1.03}}>{c.page}</h1><p style={{maxWidth:580,margin:0,color:'rgba(255,255,255,.88)',lineHeight:1.55}}>{c.intro}</p></div><div style={{minWidth:126,padding:'13px 16px',borderRadius:16,background:'rgba(15,48,41,.32)',textAlign:'center'}}><Medal size={23} color="#ffd66b"/><strong style={{display:'block',fontSize:23,marginTop:2}}>{total}</strong><span style={{fontSize:11,opacity:.82}}>{c.steps}</span></div></div></section>
    <section style={{marginTop:22,display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(210px,1fr))',gap:13}}>{TRAILS.map(trail=>{const item=progress[trail.id]||{level:1,done:[]};const selected=trail.id===active.id;return <button type="button" key={trail.id} onClick={()=>setActiveId(trail.id)} style={{textAlign:'left',cursor:'pointer',padding:17,borderRadius:17,border:selected?`2px solid ${trail.color}`:'1px solid #dce8e1',background:selected?'#fbfdfb':'white',boxShadow:selected?'0 8px 18px rgba(52,98,80,.1)':'none'}}><span style={{fontSize:26}}>{trail.emoji}</span><strong style={{display:'block',marginTop:8,fontSize:15,color:'#254a40'}}>{trail.title[lang]}</strong><small style={{display:'block',color:'#687b75',marginTop:5,lineHeight:1.35}}>{trail.sub[lang]}</small><div style={{display:'flex',justifyContent:'space-between',marginTop:13,color:trail.color,fontSize:11,fontWeight:800}}><span>{c.level} {item.level}</span><span>{item.done.length}/3</span></div></button>})}</section>
    <section style={{marginTop:22,padding:'clamp(18px,4vw,30px)',borderRadius:21,border:'1px solid #dce9e1',background:'white',boxShadow:'0 8px 22px rgba(45,79,66,.08)'}}><div style={{display:'flex',gap:14,alignItems:'center',marginBottom:20}}><div style={{width:50,height:50,borderRadius:15,display:'grid',placeItems:'center',background:`${active.color}18`,fontSize:27}}>{active.emoji}</div><div><h2 style={{margin:0,color:'#254a40',fontSize:23}}>{active.title[lang]}</h2><p style={{margin:'4px 0 0',color:active.color,fontSize:13,fontWeight:800}}>{c.level} {state.level}</p></div></div>
      {finished&&<div style={{padding:'14px 15px',marginBottom:16,borderRadius:13,background:'#fff7dc',border:'1px solid #f1d283',color:'#755716'}}><div style={{display:'flex',gap:11,alignItems:'center'}}><Medal size={24}/><div><strong>{c.medal}</strong><span style={{display:'block',fontSize:12,marginTop:2}}>{c.medalText}</span></div></div><button type="button" onClick={nextLevel} style={{marginTop:12,border:0,borderRadius:10,cursor:'pointer',padding:'9px 13px',background:'#b57920',color:'white',fontWeight:800}}>{c.continue} <ChevronRight size={16} style={{verticalAlign:'middle'}}/></button></div>}
      <div style={{display:'grid',gap:12}}>{active.lessons.map(([title,verse,text], index) => {const isDone=state.done.includes(index);const locked=index>0&&!state.done.includes(index-1);return <article key={title.pt} style={{padding:17,borderRadius:15,border:`1px solid ${isDone?'#bce0ce':'#e2e9e5'}`,background:isDone?'#f4fbf7':'white',opacity: locked ? .62 : 1}}><div style={{display:'flex',gap:11,justifyContent:'space-between',alignItems:'flex-start'}}><div><span style={{color:active.color,fontSize:11,fontWeight:900,letterSpacing:'.07em'}}>{c.step} {index+1}</span><h3 style={{margin:'3px 0 5px',color:'#28453d',fontSize:18}}>{title[lang]}</h3></div>{isDone?<CheckCircle2 size={25} color="#369568"/>:locked?<LockKeyhole size={21} color="#8da49a"/>:<BookOpen size={23} color={active.color}/>}</div><p style={{margin:'10px 0',padding:'10px 12px',borderLeft:`3px solid ${active.color}`,background:'#fafcfb',color:'#3d5e54',fontStyle:'italic',lineHeight:1.48,fontSize:14}}>{verse[lang]}</p>{locked?<p style={{margin:'9px 0 0',color:'#788b84',fontSize:13}}>{c.locked}</p>:<><p style={{color:'#586c66',lineHeight:1.55,margin:'9px 0'}}>{text[lang]}</p><p style={{color:'#315b4c',lineHeight:1.5,margin:'10px 0 14px',fontWeight:700,fontSize:13}}>{c.practice} {practice(index)}</p>{!isDone&&<button type="button" onClick={()=>complete(index)} style={{border:0,cursor:'pointer',display:'inline-flex',alignItems:'center',gap:7,padding:'9px 13px',borderRadius:10,background:active.color,color:'white',fontWeight:800}}>{c.finish}<ChevronRight size={16}/></button>}</>}</article>})}</div>
      {!finished&&<p style={{textAlign:'center',color:'#789087',margin:'18px 0 0',fontSize:12}}>{c.saved}</p>}
    </section></div>;
}
